run-name: ${{ github.actor }} Docker Image CI 🚀

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: digitalorganic/ubuntu-odoo:6.1