run-name: ${{ github.actor }} Docker Image CI 🚀

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            submodules: true
            token: ${{ secrets.TOKEN }}

      - name: Install Docker Compose
        run: |
          apt-get update && apt-get install -y docker-compose
          
      # - name: Build and run Docker Compose services
      #   run: |
      #     docker-compose -f docker-compose.build.yml build

      # - name: Push docker image
      #   run: | 
      #     echo ${{secrets.REG_TOKEN}} | docker login -u ${{secrets.REG_USER}} --password-stdin ${{secrets.REG_URL}}
      #     docker-compose -f docker-compose.build.yml push